name: sap
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.11.0
  - torchvision=0.12.0
  - cudatoolkit=11.3.1
  - numpy=1.21.5
  - matplotlib>=3.4,<3.8
  - pyyaml=6.0.2
  - scipy=1.10.1
  - tqdm=4.66.5
  - trimesh=4.5.3
  - igl
  - tensorboard=2.14.0
  - pip

